<!DOCTYPE html><html lang="zh-tw"><head><meta charset="utf-8"><meta name="X-UA-Compatible" content="IE=edge"><title> 如何在 PHP 中平順地處理 Error 及 Exception ？ · 網站製作學習誌</title><meta name="description" content="A Blog Powered By Hexo"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="short icon" href="/favicon.png"><link rel="stylesheet" href="/css/jekyll.css"><!--[if lt IE 9]>
<script src="js/html5shiv.min.js"></script>
<script src="js/respond.min.js"></script>
<![endif]--></head><body><header class="row-flex-row limit-width vh-center"><a href="/" class="logo"><img src="/favicon.png"></a><nav><ul class="nav-list"><li class="nav-list-item"><a href="/" class="nav-link">主页</a></li><li class="nav-list-item"><a href="/archives/" class="nav-link active">   博客</a></li><li class="nav-list-item"><a href="/atom.xml" class="nav-link">rss</a></li><li class="nav-list-item"><a href="https://github.com/xxxxx" target="_blank" class="nav-link">   github</a></li></ul></nav></header><div class="container limit-width"><section class="row-flex-row"><div class="post"><article class="post-block"><h2 class="post-title"><a href="/2010/04/23/1121/" class="post-title-link">如何在 PHP 中平順地處理 Error 及 Exception ？</a></h2><div class="post-meta"><ul class="post-tag-list"><li class="post-tag-item"><a href="/tags/PHP/" class="post-tag-link">PHP</a></li><li class="post-tag-item"><a href="/tags/Web-開發/" class="post-tag-link">Web 開發</a></li></ul><div class="post-time">星期二, 二月 2日 2016</div></div><div class="post-content"><p>在開發 PHP 的時候，最麻煩的事情之一就是處理錯誤。一個好的程式除了要將錯誤訊息呈現給使用者知道之外，也要讓該結束的部份正常結束才行。</p>
<p>而在 PHP5 之後，除了以往的 Error Handling 之外，還多了 Exception Handling ，使得程式變得更難去處理錯誤；所以大多數的開發者只能雙手一攤，讓這些錯誤訊息大剌剌地出現在使用者面前。</p>
<p>有沒有什麼好方法可以讓我們好好控制 Error 和 Exception 呢？</p>
<a id="more"></a>
<h2 id="傳統的做法">傳統的做法</h2><p>在很多書籍和網路範例裡，當程式出錯時就是讓程序直接死掉，最常見的就是資料庫連線：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">$link = mysql_connect(&#39;localhost&#39;, &#39;mysql_user&#39;, &#39;mysql_password&#39;);&#10;if (!$link) &#123;&#10;    die(&#39;Could not connect: &#39; . mysql_error());&#10;&#125;&#10;echo &#39;Connected successfully&#39;;&#10;mysql_close($link);</span><br></pre></td></tr></table></figure>
<p>或是在送出導向 header 後，就直接 exit ：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">header(&#34;Location: http://www.example.com/&#34;); /* Redirect browser */&#10;/* Make sure that code below does not get executed when we redirect. */&#10;exit;</span><br></pre></td></tr></table></figure>
<p>這些都不是好做法，因為有些流量較大的網站裡可能有多個資料庫連線，或是檔案的 handler 仍在開啟中；如果直接讓程序死亡或離開的話，就沒辦法將這些已經開啟的資源給正常關閉掉，進而造成系統的不穩定。</p>
<h2 id="Exception_的處理">Exception 的處理</h2><p>PHP5 中，有個 <a href="http://www.php.net/manual/en/function.set-exception-handler.php" target="_blank" rel="external">set_exception_handler</a> 這個函式，它可以幫我們處理 Exception ：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">function exception_handler($exception)&#10;&#123;&#10;  echo &#34;Uncaught exception: &#34; , $exception-&#62;getMessage(), &#34;\n&#34;;&#10;&#125;&#10;set_exception_handler(&#39;exception_handler&#39;);&#10;throw new Exception(&#39;Uncaught Exception&#39;);&#10;echo &#34;Not Executed\n&#34;;</span><br></pre></td></tr></table></figure>
<p>不過我個人認為用 <a href="http://www.php.net/manual/en/language.exceptions.php" target="_blank" rel="external">try…catch</a> 會讓我們在程式流程上的彈性更大：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">function inverse($x)&#10;&#123;&#10;    if (!$x) &#123;&#10;        throw new Exception(&#39;Division by zero.&#39;);&#10;    &#125;&#10;    else return 1/$x;&#10;&#125;&#10;try &#123;&#10;    echo inverse(5) . &#34;\n&#34;;&#10;    echo inverse(0) . &#34;\n&#34;;&#10;&#125; catch (Exception $e) &#123;&#10;    echo &#39;Caught exception: &#39;,  $e-&#62;getMessage(), &#34;\n&#34;;&#10;&#125;&#10;// Continue execution&#10;echo &#39;Hello World&#39;;</span><br></pre></td></tr></table></figure>
<p>而在我研究過 Zend Framework 的做法後，發現它在處理 Exception 上更加聰明。 Zend Framework 在 Controller 中引入一個 Response 物件，所有對瀏覽器的輸出都要經過它 (例如 Header 、 Content Body 等等) ；而這個 Reponse 物件也同時控管著 Exception 是否要被輸出到瀏覽器端，讓程式開發者能有更大的空間處理 Exception 。</p>
<p>以下我簡單把 Zend Framework 在 Response 物件中處理 Exception 的概念整理成一個自製的 Response 類別：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">class Response&#10;&#123;&#10;    private $_exceptions = array();&#10;    private $_renderExceptions = false;&#10;    public function setException(Exception $e)&#10;    &#123;&#10;        $this-&#62;_exceptions[] = $e;&#10;    &#125;&#10;    public function getExceptions()&#10;    &#123;&#10;        return $this-&#62;_exceptions;&#10;    &#125;&#10;    public function isException()&#10;    &#123;&#10;        return !empty($this-&#62;_exceptions);&#10;    &#125;&#10;    public function renderExceptions($flag = null)&#10;    &#123;&#10;        if (null !== $flag) &#123;&#10;            $this-&#62;_renderExceptions = $flag ? true : false;&#10;        &#125;&#10;        return $this-&#62;_renderExceptions;&#10;    &#125;&#10;    public function sendResponse()&#10;    &#123;&#10;        echo &#34;Header sending...\n&#34;;&#10;        $exception = &#39;&#39;;&#10;        if ($this-&#62;isException() &#38;amp;&#38;amp; $this-&#62;renderExceptions()) &#123;&#10;            foreach ($this-&#62;getExceptions() as $e) &#123;&#10;                $exception .= $e-&#62;getMessage() . &#34;\n&#34;;&#10;            &#125;&#10;            echo $exception;&#10;        &#125;&#10;        echo &#34;Body sending...\n&#34;;&#10;    &#125;&#10;&#125;</span><br></pre></td></tr></table></figure>
<p>主要的概念很簡單，就是 Response 物件先把 Exception 先收集起來，然後再視狀況如何處理，例如：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">$response = new Response();&#10;$response-&#62;renderExceptions(true); // &#35731; Exception &#21576;&#29694;&#20986;&#20358;&#10;try &#123;&#10;    // &#36889;&#35041;&#34389;&#29702;&#25105;&#20497;&#30495;&#27491;&#35201;&#22519;&#34892;&#30340;&#21205;&#20316;&#10;    throw new Exception(&#39;TEST&#39;); // &#19999;&#20986;&#19968;&#20491;&#28204;&#35430;&#29992;&#30340;&#20363;&#22806;&#10;&#125; catch (Exception $e) &#123;&#10;    $response-&#62;setException($e); // &#25910;&#38598;&#20363;&#22806;&#10;&#125;&#10;if ($response-&#62;isException()) &#123;&#10;    // &#21487;&#20197;&#22312;&#36889;&#35041;&#35352;&#37636; Exception&#10;&#125;&#10;$response-&#62;sendResponse(); // &#39023;&#31034;&#25152;&#26377;&#32080;&#26524; (&#21253;&#21547; Header, Exception, Body &#31561;)</span><br></pre></td></tr></table></figure>
<p>透過了 Response 物件來管理 Exception ，就可以不必因為 Exception 而中斷我們的程式碼。</p>
<h2 id="PHP_Error_的處理">PHP Error 的處理</h2><p>雖然 Exception 可以用 try…catch 控制程式流程，但 PHP Error 卻不行。</p>
<p>因為一般處理 PHP Error 的方法是透過 <a href="http://www.php.net/manual/en/function.set-error-handler.php" target="_blank" rel="external">set_error_handler</a>，而當執行完自訂的 Error Handler 後，我們卻只能選擇繼續執行下一行程式碼或將程式中斷離開，不然就是要利用全域變數來設定錯誤旗標以達到控制的目的。</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">$error = false;&#10;function exceptionErrorHandler($errno, $errstr, $errfile, $errline)&#10;&#123;&#10;    global $error;&#10;    $error = true;&#10;    echo $errstr, &#34;\n&#34;;&#10;    return true;&#10;&#125;&#10;set_error_handler(&#34;exceptionErrorHandler&#34;);&#10;strpos();&#10;if (!$error) &#123;&#10;    echo &#34;Do normal process here.\n&#34;;&#10;&#125;&#10;echo &#34;end.\n&#34;;</span><br></pre></td></tr></table></figure>
<p>不過 PHP5 也幫我們想好了，我們可以在 Error Handler 裡丟出 <a href="http://www.php.net/manual/en/class.errorexception.php" target="_blank" rel="external">ErrorException</a> ，就可以配合前面提到的 Response 物件做到更平順的 Exception 處理：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">function exceptionErrorHandler($errno, $errstr, $errfile, $errline )&#10;&#123;&#10;    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);&#10;&#125;&#10;set_error_handler(&#34;exceptionErrorHandler&#34;);&#10;$response = new Response();&#10;$response-&#62;renderExceptions(true); // &#35731; Exception &#21576;&#29694;&#20986;&#20358;&#10;try &#123;&#10;    // &#36889;&#35041;&#34389;&#29702;&#25105;&#20497;&#30495;&#27491;&#35201;&#22519;&#34892;&#30340;&#21205;&#20316;&#10;    trigger_error(&#39;TEST&#39;, E_USER_ERROR); // &#25913;&#29992; trigger_error &#20358;&#19999;&#20986;&#28204;&#35430;&#29992;&#37679;&#35492;&#10;&#125; catch (Exception $e) &#123;&#10;    $response-&#62;setException($e); // &#25910;&#38598;&#20363;&#22806;&#10;&#125;&#10;if ($response-&#62;isException()) &#123;&#10;    // &#21487;&#20197;&#22312;&#36889;&#35041;&#35352;&#37636; Exception&#10;&#125;&#10;$response-&#62;sendResponse(); // &#39023;&#31034;&#25152;&#26377;&#32080;&#26524; (&#21253;&#21547; Header, Exception, Body &#31561;)</span><br></pre></td></tr></table></figure>
<p>這邊最棒的是 Error Handler 丟出 ErrorException 後， try…catch 就會發生作用，而不再像 set_error_handler 這樣又返回中斷的地方繼續執行，一切就像行雲流水般那麼自然。</p>
<h2 id="結論">結論</h2><p>一個運作良好的系統必須要對錯誤的發生有最大的掌控權，而不是放任它讓系統墜毀在五里霧之中。</p>
<p>雖然前面提到的處理方式也許不是最佳的，但希望透過這樣的介紹，讓大家能夠思考自己的程式應該如何去處理錯誤這件事。</p>
<p>就寫到這裡吧，收工~</p>
</div></article><div class="pagination"><a href="/2010/04/29/1130/" class="pagination-prev">PREV</a><a href="/2010/04/23/1111/" class="pagination-next">NEXT</a></div></div><aside class="sidebar"><h3>分类标签</h3><ul class="tag-list"><li class="tag-list-item"><a class="tag-list-link" href="/tags/ASP/">ASP</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/AngularJS/">AngularJS</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/BDD/">BDD</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/Backbone-js/">Backbone.js</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/CSS/">CSS</a></li></ul><h3>最新文章</h3><ul class="post-list"><li class="post-list-item"><a class="post-list-link" href="/2015/11/09/php-closure-testing/">在 PHPUnit 中測試需要 closure 的函式</a></li><li class="post-list-item"><a class="post-list-link" href="/2015/10/27/web-testing-with-phpunit-mink/">利用 PHPUnit 與 Mink 來做 Web 測試</a></li><li class="post-list-item"><a class="post-list-link" href="/2015/10/14/what-is-test/">這樣寫測試錯了嗎？</a></li><li class="post-list-item"><a class="post-list-link" href="/2015/10/05/simple-refatoring-example-01/">邁向 PHP 重構之路 - 以 Laravel 程式碼片段為例</a></li><li class="post-list-item"><a class="post-list-link" href="/2015/07/29/laravel-mailcatcher/">在 Laravel 上用 MailCatcher 發送測試信件</a></li><li class="post-list-item"><a class="post-list-link" href="/2015/07/26/laravel-events-broadcasting/">Laravel 5.1 Events Broadcasting 實務練習</a></li><li class="post-list-item"><a class="post-list-link" href="/2015/07/08/front-end-framework-summary/">幾個有興趣的前端框架</a></li><li class="post-list-item"><a class="post-list-link" href="/2015/06/10/laravel-5-1/">Laravel 5.1 正式釋出</a></li></ul></aside></section></div><div class="extra"></div><footer class="footer"><div class="row-flex-row limit-width vh-center"><div class="copyright"><P>© 2016 <a href="/">Jace Ju</P></div><div class="power"><p><a href="http://pinggod.com/">Sean Sun</a>, 
<a href="https://hexo.io">Hexo</a>, 
<a href="https://github.com/">GitHub</a>, 
<a href="https://jekyllrb.com/">Jekyll</a></p></div></div></footer><script>(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;e=o.createElement(i);r=o.getElementsByTagName(i)[0];e.src='//www.google-analytics.com/analytics.js';r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));ga('create',"UA-65933410-1",'auto');ga('send','pageview');</script><script>var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "//hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s);})();</script><script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script></body></html>